// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {strava} from '../models';

export function AuthenticateStrava():Promise<void>;

export function GetActivities():Promise<Array<strava.Activity>>;

export function GetActivityDetail(arg1:number):Promise<strava.ActivityDetail>;

export function ProcessVideoOverlay(arg1:number,arg2:string):Promise<string>;
