// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {handlers} from '../models';
import {strava} from '../models';

export function AuthenticateStrava():Promise<void>;

export function CheckAuthenticationStatus():Promise<handlers.AuthStatus>;

export function GetActivities():Promise<Array<handlers.FrontendActivity>>;

export function GetActivitiesPage(arg1:number):Promise<handlers.PaginatedActivities>;

export function GetActivityDetail(arg1:number):Promise<strava.ActivityDetail>;

export function GetAllGPSPoints(arg1:number):Promise<Array<handlers.FrontendGPSPoint>>;

export function GetFullGPSTrajectory(arg1:number):Promise<Array<handlers.FrontendGPSPoint>>;

export function GetGPSPointForMapClick(arg1:number,arg2:number,arg3:number):Promise<handlers.FrontendGPSPoint>;

export function GetGPSPointForVideoTime(arg1:number,arg2:string):Promise<handlers.FrontendGPSPoint>;

export function GetGPSPointsWithDensity(arg1:number,arg2:string):Promise<Array<handlers.FrontendGPSPoint>>;

export function ProcessVideoOverlay(arg1:number,arg2:string,arg3:string):Promise<string>;

export function SelectVideoFile():Promise<string>;
