// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateStrava() {
  return window['go']['main']['App']['AuthenticateStrava']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetActivityDetail(arg1) {
  return window['go']['main']['App']['GetActivityDetail'](arg1);
}

export function GetAllGPSPoints(arg1) {
  return window['go']['main']['App']['GetAllGPSPoints'](arg1);
}

export function GetFullGPSTrajectory(arg1) {
  return window['go']['main']['App']['GetFullGPSTrajectory'](arg1);
}

export function GetGPSPointForMapClick(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetGPSPointForMapClick'](arg1, arg2, arg3);
}

export function GetGPSPointForVideoTime(arg1, arg2) {
  return window['go']['main']['App']['GetGPSPointForVideoTime'](arg1, arg2);
}

export function GetGPSPointsWithDensity(arg1, arg2) {
  return window['go']['main']['App']['GetGPSPointsWithDensity'](arg1, arg2);
}

export function ProcessVideoOverlay(arg1, arg2, arg3) {
  return window['go']['main']['App']['ProcessVideoOverlay'](arg1, arg2, arg3);
}

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}
