// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateStrava() {
  return window['go']['main']['App']['AuthenticateStrava']();
}

export function GetActivities() {
  return window['go']['main']['App']['GetActivities']();
}

export function GetActivityDetail(arg1) {
  return window['go']['main']['App']['GetActivityDetail'](arg1);
}

export function ProcessVideoOverlay(arg1, arg2) {
  return window['go']['main']['App']['ProcessVideoOverlay'](arg1, arg2);
}
