// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {strava} from '../models';

export function AuthenticateStrava():Promise<void>;

export function GetActivities():Promise<Array<main.FrontendActivity>>;

export function GetActivityDetail(arg1:number):Promise<strava.ActivityDetail>;

export function GetAllGPSPoints(arg1:number):Promise<Array<main.FrontendGPSPoint>>;

export function GetGPSPointForMapClick(arg1:number,arg2:number,arg3:number):Promise<main.FrontendGPSPoint>;

export function GetGPSPointForVideoTime(arg1:number,arg2:string):Promise<main.FrontendGPSPoint>;

export function ProcessVideoOverlay(arg1:number,arg2:string,arg3:string):Promise<string>;

export function SelectVideoFile():Promise<string>;
